### ISSUE TITLE
How to call logEvent from within another method

### ISSUE THREAD

**Issue by jkswope** [amplitude/react-amplitude#11]
Hi,

I am able to wrap the <Amplitude /> component around other components/elements in render without any issues. I need to be able to fire logEvent from another method that is called from a click event that calls a post. I need to send the results of that post to the eventProperties of the logEvent. Is this possible, or do I need to use the standard amplitude js sdk?

```
import { Amplitude } from '@amplitude/react-amplitude'
...
class myForm extends React.Component {
// the submit method
handleInputChange = input => {
    const sendFormResult = this.props.getResponseFromApi(input)
    sendFormResult.then(response => {
      if (response) {
        // call amplitude here, send logEvent and eventProperties
        console.log(response)
      }
    }, error => {
        // call amplitude here, send logEvent and eventProperties
      console.error(error)
    })
  }
...
// in render()
<form onSubmit={this.props.handleSubmit(this.handleInputChange)}>
<Button type='submit'>
   Submit
</Button>
...
}
```

**Comment by ryanashcraft** [comment]
@jkswope You have a few options. You could pass the logEvent as a parameter to your handler function. Or you can set a ref on the Amplitude component and use that to log the event (e.g. `this.amplitudeRef.logEvent('my event', myProps)`). Or you can render an Amplitude component on the parent component of myForm and pass `logEvent` as a prop to `myForm`.

A future potential improvement to this library would provide another option. We could provide a high-order component API so you can have logEvent or the amplitude instance passed as a prop to the component.

**Comment by jkswope** [comment]
@ryanashcraft Thanks for your prompt response!

I'm not sure how I would pass the logEvent in onSubmit={this.props.handleSubmit(this.handleInputChange)}. It is looking like wrapping the parent component might be best.
```
<Amplitude ref={a => this.amplitudeRef = a}>
<Button type='submit'>
   Submit
</Button>
</Amplitude>
```

And then call it from within handleInviteCodeChange as you stated above -`this.amplitudeRef.logEvent('my event', myProps)`

There is a situation where I am calling an api, and populating Redux, then passing the redux var as a prop into a parent component, when it loads. I need to pass that response/redux value as an eventProperty. Can I use LogOnMount to do that?

**Comment by ryanashcraft** [comment]
@jkswope Sorry for delayed response this time around.

I was proposing something like this for passing logEvent as a param to a handler:

```
<Amplitude>
  {({ logEvent }) => (
    <Button type="submit" onClick={this.props.handleSubmit.bind(this, logEvent)}>
       Submit
    </Button>
</Amplitude>
```

The ref example you showed looks good.

Sounds like LogOnMount would work nicely for that use case. For example:

```
{!!props.data && <LogOnMount eventType="data loaded" />}
```

**Comment by jkswope** [comment]
Thank you!
