### ISSUE TITLE
How to setUserId

### ISSUE THREAD

**Issue by jkswope** [amplitude/react-amplitude#15]
Hi,

I need to send the User ID to amplitude once a user logs in to my app. I found documentation from the amplitude sdk that allows for adding a `setUserId(userId)` property to the amplitude instance - (https://amplitude.zendesk.com/hc/en-us/articles/115002889587#methods - #14). I am uncertain on how to add this to react-amplitude. 

Do you have any advice on how to set it? 

Does it have to be set on each <Amplitude /> instance?

![image](https://user-images.githubusercontent.com/36052240/53497222-b7bf6500-3a71-11e9-9cd9-5407dbcb58e9.png)

**Comment by ryanashcraft** [comment]
@jkswope There's a `userId` prop on the AmplitudeProvider that does tihs. Have you tried that?

**Comment by jkswope** [comment]
Oh. I'm sorry. I missed reading about that prop in the documentation.
